#!/usr/bin/env python

import sys
import json
import argparse

import jsoncat

def main():
	parser = argparse.ArgumentParser("Pretty-print streams of json objects")
	parser.add_argument("input", type=str, nargs="?")
	args = parser.parse_args()

	if args.input and args.input != "-":
		f = open(args.input)
	else:
		f = sys.stdin

	for obj in jsoncat.loads(f.read()):
		print(json.dumps(obj, indent=4, separators=(',', ': ')))


if __name__ == '__main__':
	main()
